<?php

/**
 * @file
 * Contains openid_connect_eufidp.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function openid_connect_eufidp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the openid_connect_eufidp module.
    case 'help.page.openid_connect_eufidp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OpenID Connect client for the EUF IdP') . '</p>';
      return $output;

    default:
  }
}
