# Schema for the configuration files of the OpenID Connect EUF IdP module.
openid_connect.client.plugin.eufidp:
  type: mapping
  label: 'OpenID Connect EUF IdP settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client secret'
    iss_allowed_domains:
      type: string
      label: 'Domains that are allowed to initiate SSO using ISS'
    environment:
      type: string
      label: 'Environment'
    scopes:
      type: sequence
      label: 'Scopes'
      sequence:
        type: string
